import mongoose from "mongoose";

const CallRecordSchema = new mongoose.Schema({
  orderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "ZomatoOrder",
    required: true,
  },
  
  tabId: { type: String }, 
  call_to_number: { type: String },
  
  id: { type: String },
  call_id: { type: String },
  uuid: { type: String },
  direction: { type: String },
  description: { type: String },
  detailed_description: { type: String },
  status: { type: String },
  blocked_number_id: { type: String },
  recording_url: { type: String },
  service: { type: String },
  date: { type: String },
  time: { type: String },
  end_stamp: { type: String },
  broadcast_id: { type: String },
  dtmf_input: { type: String },
  call_duration: { type: Number },
  answered_seconds: { type: Number },
  minutes_consumed: { type: Number },
  charges: { type: Number },
  department_name: { type: String },
  agent_number: { type: String },
  agent_number_with_prefix: { type: String },
  agent_name: { type: String },
  client_number: { type: String },
  did_number: { type: String },
  reason: { type: String },
  hangup_cause: { type: String },
  notes: { type: String },
  contact_details: { type: mongoose.Schema.Types.Mixed },
  missed_agents: [{ type: mongoose.Schema.Types.Mixed }],
  call_flow: [{ type: mongoose.Schema.Types.Mixed }],
  accountid: { type: String },
  agent_ring_time: { type: String },
  circle: {
    operator: { type: String },
    circle: { type: String },
  },
  agent_hangup_data: { type: mongoose.Schema.Types.Mixed },
  transfer_missed_agent: [{ type: mongoose.Schema.Types.Mixed }],
  call_hint: { type: String },
  support_api_call: { type: Boolean },
  lead_id: { type: String },
  sid: { type: String },
  sname: { type: String },
  is_incoming_from_broadcast: { type: Boolean },
  caller_id_num: { type: String },
  sip_agent_ids: { type: mongoose.Schema.Types.Mixed },
  dialer_call_details: { type: mongoose.Schema.Types.Mixed },
  custom_status: { type: String },
  is_whatsapp: { type: Number },
  u_contact_name: { type: String },
  u_contact_id: { type: String },
  ref_id: { type: String },
  total_call_duration: { type: Number },
  is_sip_trunk_call: { type: Boolean },
  lead_data: [{ type: mongoose.Schema.Types.Mixed }],
  voicemail_recording: { type: Boolean },
  extension_c2c: { type: String },
  aws_call_recording_identifier: { type: String },
  call_status: { type: String },
  customer_ring_time: { type: String },
  caller_id_number: { type: String },
  
  webhook_payload: { type: mongoose.Schema.Types.Mixed },
}, { timestamps: true });

if (mongoose.models.CallRecord) {
  delete mongoose.models.CallRecord;
}
export default mongoose.model("CallRecord", CallRecordSchema);
